### ISSUE TITLE
Environment to run noaa sst append notebook?

### ISSUE THREAD

**Issue by rsignell** [zarr-developers/VirtualiZarr#435]
When I run the noaa sst append notebook, I'm getting the error:
```
TypeError: Expected a BytesBytesCodec. Got <class 'numcodecs.zarr3.FixedScaleOffset'> instead.
```
when executing the `virtual_ds.virtualize.to_icechunk(session.store)` cell. 

I'm guessing this is an environment problem? I created the environment using this conda `environment.yml` file:
``` yml
name: icechunk
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - aiohttp
  - coiled
  - dask
  - fsspec
  - h5netcdf
  - icechunk
  - ipywidgets
  - ipykernel
  - jupyterlab
  - python-dotenv
  - s3fs
  - virtualizarr
  - xarray
 ```
which results in:
```
(icechunk) rsignell@OSC:~$ conda list | grep -E "zarr|numcodecs|icechunk|virtualizarr|xarray"
# packages in environment at /home/rsignell/miniforge3/envs/icechunk:
icechunk                  0.1.3           py312h12e396e_1    conda-forge
numcodecs                 0.15.1          py312hf9745cd_0    conda-forge
virtualizarr              1.3.0              pyhd8ed1ab_0    conda-forge
xarray                    2025.1.2           pyhd8ed1ab_0    conda-forge
zarr                      3.0.3              pyhd8ed1ab_0    conda-forge
```
